const abi = [
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_token",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_govToken",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_busd",
            "type":"address"
         },
         {
            "internalType":"address",
            "name":"_vault",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"_start",
            "type":"uint256"
         }
      ],
      "stateMutability":"nonpayable",
      "type":"constructor"
   },
   {
      "inputs":[
         
      ],
      "name":"HadesFountain__InvalidMinimum",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"pending",
            "type":"uint256"
         }
      ],
      "name":"HadesFountain__InvalidPendingAmount",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"HadesFountain__InvalidUpline",
      "type":"error"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"HadesFountain__InvalidUser",
      "type":"error"
   },
   {
      "inputs":[
         
      ],
      "name":"HadesFountain__MaxPayoutReached",
      "type":"error"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"AddLotteryFunds",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_sender",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"_receiver",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"Airdrop",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_time",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint8",
            "name":"_level",
            "type":"uint8"
         }
      ],
      "name":"Boost",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_total",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_realized",
            "type":"uint256"
         }
      ],
      "name":"Deposit",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_realized",
            "type":"uint256"
         }
      ],
      "name":"FaucetClaim",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_total",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_effective",
            "type":"uint256"
         }
      ],
      "name":"FaucetCompound",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"uint8",
            "name":"_index",
            "type":"uint8"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         }
      ],
      "name":"FlameHoldLevelTweak",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":false,
            "internalType":"string",
            "name":"_event",
            "type":"string"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_value",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"address",
            "name":"_add",
            "type":"address"
         }
      ],
      "name":"LogEvent",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"uint8",
            "name":"_level",
            "type":"uint8"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_newDirect",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_directLeaders",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_structureTotal",
            "type":"uint256"
         }
      ],
      "name":"ModRequirements",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"previousOwner",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"OwnershipTransferred",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_realized",
            "type":"uint256"
         }
      ],
      "name":"RebaseClaim",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_realized",
            "type":"uint256"
         }
      ],
      "name":"RebaseCompound",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_leader",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_resetCount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"_level",
            "type":"uint256"
         }
      ],
      "name":"ResetLeader",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_sender",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"_receiver",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         },
         {
            "indexed":false,
            "internalType":"uint8",
            "name":"level",
            "type":"uint8"
         },
         {
            "indexed":false,
            "internalType":"uint8",
            "name":"time",
            "type":"uint8"
         }
      ],
      "name":"SuperDrop",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_upline",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"UplineAdded",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_triggered",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"_upline",
            "type":"address"
         },
         {
            "indexed":false,
            "internalType":"uint8",
            "name":"downline",
            "type":"uint8"
         },
         {
            "indexed":false,
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "name":"UplineAidrop",
      "type":"event"
   },
   {
      "anonymous":false,
      "inputs":[
         {
            "indexed":true,
            "internalType":"address",
            "name":"_newUpline",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "indexed":true,
            "internalType":"address",
            "name":"_prevUpline",
            "type":"address"
         }
      ],
      "name":"UplineChanged",
      "type":"event"
   },
   {
      "inputs":[
         
      ],
      "name":"DIVFACTOR",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"MAX_PAYOUT",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"REBASE_REWARD",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"REBASE_TIMER",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"accounting",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"netFaucet",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"deposits",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"rolls",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"rebaseCompounded",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"airdrops_rcv",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"airdrops_pending",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"accFaucet",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"accRebase",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"rebaseCount",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"lastAction",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"faucetPenaltyDailyValue",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"done",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_receiver",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"bool",
            "name":"fromPending",
            "type":"bool"
         }
      ],
      "name":"airdrop",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"boostPriceFactor",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"boostPrice_1",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"boostPrices",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_rebase",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "components":[
               {
                  "internalType":"uint256",
                  "name":"faucetClaims",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"rebaseClaims",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"faucetEffectiveClaims",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"rebaseEffectiveClaims",
                  "type":"uint256"
               },
               {
                  "internalType":"uint256",
                  "name":"boostEnd",
                  "type":"uint256"
               },
               {
                  "internalType":"uint8",
                  "name":"boostLvl",
                  "type":"uint8"
               }
            ],
            "internalType":"struct HadesFountain.Claims",
            "name":"_claim",
            "type":"tuple"
         },
         {
            "internalType":"uint256",
            "name":"userRebases",
            "type":"uint256"
         }
      ],
      "name":"boostRebase",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"_updatedRebase",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"boostTime",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"boostTreasury",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"busd",
      "outputs":[
         {
            "internalType":"contract IERC20",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"calculateRebase",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"_totalRebase",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_userRebase",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_totalRebaseCount",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_percent",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"claim",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"claims",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"faucetClaims",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"rebaseClaims",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"faucetEffectiveClaims",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"rebaseEffectiveClaims",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"boostEnd",
            "type":"uint256"
         },
         {
            "internalType":"uint8",
            "name":"boostLvl",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"compoundAll",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"compoundAuto",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"compoundFaucet",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"compoundRebase",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_amount",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"_upline",
            "type":"address"
         }
      ],
      "name":"deposit",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"discounts",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"discount",
            "type":"uint8"
         },
         {
            "internalType":"uint256",
            "name":"amount",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_idx",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_time",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_price_1",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_price_factor",
            "type":"uint256"
         }
      ],
      "name":"editBoost",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"baseLevel",
            "type":"uint256"
         },
         {
            "internalType":"uint8",
            "name":"levelUp",
            "type":"uint8"
         },
         {
            "internalType":"uint256",
            "name":"basePrice",
            "type":"uint256"
         }
      ],
      "name":"editBoostBasePrice",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"idx",
            "type":"uint8"
         },
         {
            "internalType":"uint8",
            "name":"_discount",
            "type":"uint8"
         },
         {
            "internalType":"uint256",
            "name":"_maxThreshold",
            "type":"uint256"
         }
      ],
      "name":"editDiscounts",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"_level",
            "type":"uint8"
         },
         {
            "internalType":"uint256",
            "name":"_directRef",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_directLeaders",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_structureTotal",
            "type":"uint256"
         }
      ],
      "name":"editLevelRequirements",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"faucetPayout",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"grossPayout",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"netPayout",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"sustainabilityFee",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"getNerdData",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"_grossClaimed",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_netFaucetValue",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_grossFaucetValue",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_faucetPayout",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_faucetMaxPayout",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_rebasePayout",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"_nerdPercent",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"getTotalRebaseCount",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"govLevelHold",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"govToken",
      "outputs":[
         {
            "internalType":"contract IERC20",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "internalType":"uint8",
            "name":"_level",
            "type":"uint8"
         }
      ],
      "name":"isBalanceCovered",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         }
      ],
      "name":"isNetPositive",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"kickback",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"leadOrLotto",
      "outputs":[
         {
            "internalType":"bool",
            "name":"",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"leaders",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"resets",
            "type":"uint8"
         },
         {
            "internalType":"uint8",
            "name":"lastResetLvl",
            "type":"uint8"
         },
         {
            "internalType":"bool",
            "name":"migrated",
            "type":"bool"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"maxRefDepth",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"maxWhaleBracket",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"minDrop",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"minimumInitial",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"owner",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"payoutLevelBonus",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"pol",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"renounceOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "name":"req",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"directReferrals",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"directTeamLeaders",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"structureTotal",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"_treasuryAmount",
            "type":"uint8"
         }
      ],
      "name":"setBoostTreasury",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_increase",
            "type":"uint256"
         }
      ],
      "name":"setCapLevelIncrease",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8",
            "name":"index",
            "type":"uint8"
         },
         {
            "internalType":"uint256",
            "name":"_val",
            "type":"uint256"
         }
      ],
      "name":"setGovHold",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint8[5]",
            "name":"_kicks",
            "type":"uint8[5]"
         }
      ],
      "name":"setKickbacks",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"_newVal",
            "type":"uint256"
         }
      ],
      "name":"setMinimumInitial",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"start",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "name":"team",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"referrals",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"upline",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"upline_set",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"refClaimRound",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"match_bonus",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"lastAirdropSent",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"airdrops_sent",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"structure",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"maxDownline",
            "type":"uint256"
         },
         {
            "internalType":"uint256",
            "name":"referralsToUpdate",
            "type":"uint256"
         },
         {
            "internalType":"address",
            "name":"prevUpline",
            "type":"address"
         },
         {
            "internalType":"uint256",
            "name":"leaders",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "name":"timeWarp",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"token",
      "outputs":[
         {
            "internalType":"contract IERC20",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"total_airdrops",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"total_claims",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"total_deposits",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"total_users",
      "outputs":[
         {
            "internalType":"uint256",
            "name":"",
            "type":"uint256"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"newOwner",
            "type":"address"
         }
      ],
      "name":"transferOwnership",
      "outputs":[
         
      ],
      "stateMutability":"nonpayable",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"uplineUpdater",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         {
            "internalType":"address",
            "name":"_user",
            "type":"address"
         },
         {
            "internalType":"bool",
            "name":"getBoosted",
            "type":"bool"
         }
      ],
      "name":"userLevel",
      "outputs":[
         {
            "internalType":"uint8",
            "name":"_level",
            "type":"uint8"
         },
         {
            "internalType":"uint8",
            "name":"currentBoost",
            "type":"uint8"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   },
   {
      "inputs":[
         
      ],
      "name":"vault",
      "outputs":[
         {
            "internalType":"address",
            "name":"",
            "type":"address"
         }
      ],
      "stateMutability":"view",
      "type":"function"
   }
] as const;

export default abi;